encrypted = "GLKDOHADHZAVILAOLPUZJYPWAPVUOLDHZUVDOHSMDHFAOYVBNOAOVBZOHSAUVAJVTTPAOLYJOLLYMBSMYPLUKZHDOLYSVVRPUNZAVWWLKOPZIYBZOHUKZOVBALKPMFVBDHUAAVHZRMVYLKPMPJHAPVUVUAOLZLAOPUNZVMTVTLUAAOLYLZHCLYFLHYULZANVVKTHUNVPUNAVWYLHJOHJOHYPAFZLYTVUAVKHFPUAOLWHYPZOFVBHYLNVPUNAVTYJSHYLVMLTTPUZALYPTUVAVMOPZWLYZBHZPVUUVDIBAOLZHNVVKTHUHUKOLSSLEWVBUKHZDLSSHZHUFWHYZVUPRUVDADHZOLILNHUAOLDVYRPUTLIBAALZZKPKUVAHUZDLYZOLAOYVIIPUNSFYLZBTLKOLYDHSROLYLFLZMPELKVUAOLNYVBUKWVVOPKVUAILSPLCLNVKZHPKZBJOAOPUNZZOLTBYTBYLKJVUALTWABVBZSFDOLUOLYMSBZOOHKKPLKHDHFHWSBTLVMZTVRLZVHYLKBWZBKKLUSFMYVTOLYMHAOLYZJOPTULFAOLZPNOAVMDOPJOTHKLOLYOLHYAHJOLAOLHZWLJAVMAOLPUALYPVYDOLUZOLYLHJOLKPATHKLOLYOLHYAHJOLTVYLOLYTVAOLYDOVOHKQBZAJVTLKVDUZAHPYZABYULKAVNYLLAOLYMYVTAOLMPYLWSHJLDOLYLZOLDHZRPUKSPUNIHYRLKVHRADPNZBUKLYAOLIYLHRMHZARLAASLAOLFVBUNJOPSKYLUDLYLZAPSSHIVCLHZDHZHSZVOLYMHAOLYPAILPUNZBUKHFTV"
done = False
tess26 = open("data/tess26.txt", "r").readline()
decrypted = encrypted

i = 1

while not done:
    temp = ""
    print("Attempt number " + str(i))
    for letter in decrypted:
        if ord(letter) == 90:
            letter = "A"
        else:
            letter = chr(ord(letter) + 1)
        temp += letter

    if temp in tess26:
        decrypted = temp
        done = True
        print("It's been decrypted! Text is: " + decrypted)
    else:
        decrypted = temp
        done = False
    i = i + 1

print("done!")
