ENCRYPTED = "GOAHIAEMTAAIDEGGHSPAINEIOCONCATVHUDNNWOLTNNTKTBKOOLOUNUMIABYHFTNSOBCVRTDBHRUREHHREPUTTWLEGAHCSMENUECEAHENTSFELHEOIOPMATSAPYAUNVYHNNRWELTSNEPHIYINBAISRTNOFHHEOENLGTFUOWWLSAEIGBSDAMLHGOHIHYIUULRLGOETLOIIWOETNYEEDCHREVTFWAEEDOAGOIOYESEOOOTGRCATNIREESCNMEITDUIYNIEPIONRNEOEASEHRIDEDSLTNFMGSTLHETSFIITMFRDIHMILMNHAMTRSHEUESIWIEUTNETNRTHMSFUSYKUNMHBWOECSRHAEERETUHDRVISROLTNOLKSRFURHEHLHSCEDXIHEURCHWTSSDSPSSUOSOWUORESAIDEYLPAOGRDHETLEDHTBTMBEHIHAIOTDEMIREIITTESDBNINATHGRHGGOIEALSTHETGSAEHBAHHHIURAEAHTIHTASEEIIHGUSEUNHTAOLAWEBHTTPOADPFAEIDIEWWEDIIFETIIRYAETFOSOEEIFAOUINHBFTIEEIMEAANUTMRSBKELEDNLHHNPHEGTKTWIWEISEFSRTEDIEDSTETDAENAEEMSTKSBEUCIOIUYNNVMAAHDNEEHYWYNEMYSAHRNSCOANSTENLHORENMCCLTNDSTNEENPUTANGWMRSCEUEHSANNITNMGMIYEHENAEWIGYOAUEECIHIEINIDNCDAFPIXOCWAAOLSOTDDNOAIEOTEOIRHTPLPOOGEERNETKRRBIPMIREWHIAEOTANCNAHSGFARHSGEOAIHTIEPTVEOIAMKL"
TESS26 = open("data/tess26.txt", "r").readline()

for columns in range(4, 7):
    columnLength = int(len(ENCRYPTED) / columns)

    rows = [ENCRYPTED[i * columnLength:i * columnLength + columnLength] for i in range(columns)]

    decrypted = "".join([rows[row][letter] for letter in range(len(rows[0])) for row in range(len(rows))])

    if decrypted in TESS26:
        print("It's been decrypted! Text is: " + decrypted)
    elif columns == 6:
        print("Decryption failed!  Text is: " + decrypted)
