ENCRYPTED = "GOAHIAEMTAAIDEGGHSPAINEIOCONCATVHUDNNWOLTNNTKTBKOOLOUNUMIABYHFTNSOBCVRTDBHRUREHHREPUTTWLEGAHCSMENUECEAHENTSFELHEOIOPMATSAPYAUNVYHNNRWELTSNEPHIYINBAISRTNOFHHEOENLGTFUOWWLSAEIGBSDAMLHGOHIHYIUULRLGOETLOIIWOETNYEEDCHREVTFWAEEDOAGOIOYESEOOOTGRCATNIREESCNMEITDUIYNIEPIONRNEOEASEHRIDEDSLTNFMGSTLHETSFIITMFRDIHMILMNHAMTRSHEUESIWIEUTNETNRTHMSFUSYKUNMHBWOECSRHAEERETUHDRVISROLTNOLKSRFURHEHLHSCEDXIHEURCHWTSSDSPSSUOSOWUORESAIDEYLPAOGRDHETLEDHTBTMBEHIHAIOTDEMIREIITTESDBNINATHGRHGGOIEALSTHETGSAEHBAHHHIURAEAHTIHTASEEIIHGUSEUNHTAOLAWEBHTTPOADPFAEIDIEWWEDIIFETIIRYAETFOSOEEIFAOUINHBFTIEEIMEAANUTMRSBKELEDNLHHNPHEGTKTWIWEISEFSRTEDIEDSTETDAENAEEMSTKSBEUCIOIUYNNVMAAHDNEEHYWYNEMYSAHRNSCOANSTENLHORENMCCLTNDSTNEENPUTANGWMRSCEUEHSANNITNMGMIYEHENAEWIGYOAUEECIHIEINIDNCDAFPIXOCWAAOLSOTDDNOAIEOTEOIRHTPLPOOGEERNETKRRBIPMIREWHIAEOTANCNAHSGFARHSGEOAIHTIEPTVEOIAMKL"

for columns in range(4, 7):
    print("Attempting with key " + str(columns))

    rows = []
    columnLength = int(len(ENCRYPTED) / columns)
    for i in range(columns):
        rows.append(ENCRYPTED[i * columnLength:i * columnLength + columnLength])

    decrypted = ""
    for letter in range(len(rows[0])):
        for row in range(len(rows)):
            decrypted += rows[row][letter]

    TESS26 = open("data/tess26.txt", "r").readline()
    if decrypted in TESS26:
        print("It's been decrypted! Text is: " + decrypted)
    else:
        print("Decryption failed!  Text is: " + decrypted)
